spring:
  application:
    name: msspt
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 10000
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

mss:
  api-url: ${API_URL}
  product-url: ${PRODUCT_URL}
  proxy:
    free-list-url: ${PROXY_FREE_LIST_URL}
    paid-host: ${PROXY_PAID_HOST}
    paid-port: ${PROXY_PAID_PORT}
