spring:
  application:
    name: msspt
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

mss:
  api-url:
    catalog-page-size: 100
    catalog-by-category-and-page-and-size-url: ${CATALOG-BY-CATEGORY-AND-PAGE-AND-SIZE-URL}
    request-delay-millis: 500
