spring:
  application:
    name: msspt
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

mss:
  api-url:
    page-size: 100
    products-by-category-and-page-and-size-url: ${PRODUCTS-BY-CATEGORY-AND-PAGE-AND-SIZE-URL}
